config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root to: 'welcome#index'
  devise_for :users
  resources :wikis do
    resources :collaborators, only: [:new, :create, :destroy]
  end
  patch '/downgrade' => 'users#downgrade', as: :downgrade
  resources :charges, only: [:new, :create]
end

app/models/amount.rb
class Amount
	def self.default
		15_00
	end
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :wiki
  belongs_to :user
  validates :wiki_id, presence: true
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :wikis
  has_many :collaborators
  has_many :wikis, through: :collaborators
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
	belongs_to :user
  has_many :users, through: :collaborators
  has_many :collaborators

  validates :title, presence: true
	validates :body, presence: true
	validates :user_id, presence: true
	include FriendlyId

  friendly_id :slug_cadidates, use: :slugged

  def slug_cadidates
    [:title, [:title, user.name]]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include Pundit

  rescue_from Pundit::NotAuthorizedError do |exception|
  	redirect_to wikis_path, alert: "Nope. Can't go there!"
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  	@stripe_btn_data = {
  		key: "#{Rails.configuration.stripe[:publishable_key]}",
  		description: 'Premium Membership - #{current_user.name}',
  		amount: Amount.default
  	}
  end

  def create
  	# Creates a Stripe Customer object, for associating with the charge
  	customer = Stripe::Customer.create(
  		email: current_user.email,
  		card: params[:stripeToken]
  	)

  	# Where the real magic happens
  	charge = Stripe::Charge.create(
  		customer: customer.id, # Note -- this is NOT the user_id in your app
  		amount: Amount.default,
  		description: 'Premium Membership - #{current_user.email}',
  		currency: 'usd'
  	)

  	flash[:notice] = 'Transaction successful'
    current_user.update_attributes(role: 'premium')
  	redirect_to wikis_path

  	# Stripe will send back CardErrors, with friendly messages
  	# when something goes wrong.
  	# This 'rescue block' catches and displays those errors.
  	rescue Stripe::CardError => e
  	flash[:error] = e.message
  	redirect_to new_charge_path
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  def new
  	@collab = Collaborator.new
  	@wiki = Wiki.friendly.find(params[:wiki_id])
  end

  def create
  	@wiki = Wiki.friendly.find(params[:wiki_id])
  	@collab = @wiki.collaborators.build(collab_params)
  	if @collab.user = User.find_by(email: @collab.email)
  	else
  		flash[:alert] = "Invalid User"
  	end

  	if @collab.save
  		flash[:notice] = "Nice add!"
  		redirect_to new_wiki_collaborator_path
  	else
  		flash[:error] = 'Please try again'
  		redirect_to new_wiki_collaborator_path
  	end
  end

  def destroy
  	@collab = Collaborator.find(params[:id])
  	if @collab.destroy
  		flash[:notice] = "Collaborator removed"
  		redirect_to new_wiki_collaborator_path
  	else
  		flash[:error] = "There was a problem deleting. Please try again."
  		redirect_to new_wiki_collaborator_path
  	end
  end

  private

  def collab_params
  	params.require(:collaborator).permit(:user_id, :wiki_id, :email)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def show

	end

	def downgrade
		if current_user.update_attribute(:role, 'standard')
			current_user.wikis.where(private: true).each do |wiki|
				wiki.update_attributes(private: false)
			end
			flash[:notice] = "nice!"
			redirect_to wikis_path
		end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  def index
    @wikis = policy_scope(Wiki)
    
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end

  def create
    @wiki = current_user.wikis.build(wiki_params)
    @wiki.user = current_user
    authorize @wiki
    if @wiki.save
      flash[:notice] = "Saved!"
      redirect_to wikis_path
    else
      flash[:error] = "Nope"
      render :new
    end
  end

  def edit
    @wiki = Wiki.friendly.find(params[:id])
    authorize @wiki
  end

  def show
    @wiki = Wiki.friendly.find(params[:id])
    authorize @wiki
  end

  def update
    @wiki = Wiki.friendly.find(params[:id])
    authorize @wiki
    if @wiki.update_attributes(wiki_params)
      redirect_to wiki_path(@wiki)
    else
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.friendly.find(params[:id])
    authorize @wiki
    if @wiki.destroy
      redirect_to wikis_path
    else
      redirect_to wiki_path(@wiki)
    end
  end

  private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private, :user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/wikis_helper.rb
module WikisHelper
	def markdown(words)
		renderer = Redcarpet::Render::HTML.new
		redcarpet = Redcarpet::Markdown.new(renderer, extensions = {})
		(redcarpet.render words).html_safe
	end
end

app/views/charges/new.html.erb
<h1>Payment</h1>
<%= form_tag charges_path do %>
	<h4>Click the button!</h4>
	<script class='stripe-button' src='https://checkout.stripe.com/checkout.js' data-key='<%=@stripe_btn_data[:key] %>' data-amount=<%= @stripe_btn_data[:amount] %> data-description='<%= @stripe_btn_data[:description] %>'></script>
<% end %>

app/views/charges/new.html.haml
%h1 Payment
= form_tag charges_path do
  %h4 Click the button!
  %script.stripe-button{"data-amount" => "<haml_loud", "data-key" => @stripe_btn_data[:key], :src => "https://checkout.stripe.com/checkout.js"}
    :cdata
      @stripe_btn_data[:amount]

-# I couldn't figure this one out so i cheated

app/views/collaborators/new.html.erb
<h1>Collaborators</h1>

<%= form_for [@wiki, @collab] do |f| %>
	<div class='form-group'>
		<%= f.label :email %>
		<%= f.text_field :email, class: 'form-control' %>
	</div>
	<%= f.submit "Add", class: 'btn btn-success' %>
<% end %>
Current Collaborators (click to remove): 
<% @wiki.collaborators.each do |col| %>
	<br><%= link_to col.user.name, [@wiki, col], method: :delete %>
<% end %>
<p><%= link_to "Back", edit_wiki_path(@wiki) %></p>

app/views/collaborators/new.html.haml
%h1 Collaborators
= form_for [@wiki, @collab] do |f|
  .form-group
    = f.label :email
    = f.text_field :email, class: 'form-control'
  = f.submit "Add", class: 'btn btn-success'
Current Collaborators:
- @wiki.collaborators.each do |col|
  %br
  = link_to col.user.name, [@wiki, col], method: :delete
%p= link_to "Back", edit_wiki_path(@wiki)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='en'>
<head>
  <title>Workoutwiki</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<div class='container'>
	<ul class='nav nav-pills'>
		<li><%= link_to "Home", root_path %></li>
		<li><%= link_to 'Workouts', wikis_path %></li>
		<li><%= link_to 'New Wiki', new_wiki_path %></li>
	<% if current_user %>
		<div class='pull-right dropdown'>
		  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
		    <%= current_user.name %>
		    <span class="caret"></span>
		  </button>
		  <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
		    <li role="presentation"><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
		    <li role='presentation'><%= link_to "Edit Account", edit_user_registration_path(current_user) %></li>
		  </ul>
		</div>
	<% end %>
	</ul>

	<div id='flash-container'>
		<% if flash[:notice] %>
			<div id='flash-notice'class='alert alert-success'>
				<button type='button' class='close' data-dismiss='alert'>&times;</button>
				<%= flash[:notice] %>
			</div>
		<% elsif flash[:alert] %>
			<div class='alert alert-warning'>
				<button type='button' class='close' data-dismiss='alert'>&times;</button>
				<%= flash[:alert] %>
			</div>
		<% elsif flash[:error] %>
			<div class='alert alert-danger'>
				<button type='button' class='close' data-dismiss='alert'>&times;</button>
				<%= flash[:error] %>
			</div>
		<% end %>
	</div>
	
	<%= yield %>
</div>
</body>
</html>

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title Workoutwiki
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1'}
  %body
    .container
      %ul.nav.nav-pills
        %li= link_to "Home", root_path
        %li= link_to "index", wikis_path
        %li= link_to "new", new_wiki_path
        - if current_user
          .pull-right.dropdown
            %button.btn.btn-default.dropdown-toggle#dropdownMenu1{ type: 'button', "data-toggle" => 'dropdown', "aria-expanded" => 'true'}
              = current_user.name
              %span.caret
            %ul.dropdown-menu{ role: 'menu', "aria-labelledby" => 'dropdownMenu1'}
              %li{role: 'presentation'}
                = link_to "Sign Out", destroy_user_session_path, method: :delete
              %li{role: 'presentation'}
                = link_to "Edit Account", edit_user_registration_path(current_user)
      #flash-container
        - if flash[:notice]
          #flash-notice.alert.alert-success
            %button.close{"data-dismiss" => "alert", :type => "button"} ×
            = flash[:notice]
        - elsif flash[:alert]
          .alert.alert-warning
            %button.close{type: 'button', "data-dismiss" => 'alert'} ×
            = flash[:alert]
        - elsif flash[:error]
          .alert.alert-danger
            %button.close{type: 'button', "data-dismiss" => 'alert'} ×
            = flash[:error]
      = yield

app/views/welcome/index.html.erb
<div class="row">
  <div class="jumbotron">
    <h1>Workout Wiki</h1>
    <p>This is a place where people come together and share their own creative workouts.</p>
    <p>
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#signInModal">
        Sign In
      </button> or
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#signUpModal">
        Sign Up
      </button> today!
      <!-- Sign in Modal -->
      <div class="modal fade" id="signInModal" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h2 class="modal-title" id="myModalLabel">Sign In</h2>
            </div>
            <div class="modal-body">
              <%= render 'devise/sessions/new' %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            </div>
          </div>
        </div>
      </div>

      <!-- Sign up Modal -->
      <div class="modal fade" id="signUpModal" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h2 class="modal-title" id="myModalLabel">Sign Up</h2>
            </div>
            <div class="modal-body">
              <%= render 'devise/registrations/new' %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            </div>
          </div>
        </div>
      </div>
    </p>
  </div>
</div>
<div class='row'>
  <div class='col-md-10 col-md-offset-1'>
    <h4>
      Is your gym routine getting old? Don't have money for a personal trainer? Well Look no further.  Workout Wiki is the collection of knowledge of work-out enthusiasts like yourself.  Here we post our specific know-hows of different excercises classified by body parts, the 'don'ts' of famous excersices, and healthy alternatives.
    <h4>
  </div>
</div>
<div class='row'>
  <div class='col-md-4'>
    <h2>Sign up for a free account</h2>
    <p>With a standard membership, you will be able to create and edit any public wikis</p>
  </div>
  <div class='col-md-4'>
    <h2>Upgrade to premium!</h2>
    <p>If you upgrade to a premium account, you will have the power to create your own private wikis, and can choose the people you want to see and contribute to it.
  </div>
  <div class='col-md-4'>
    <h2>Browse as a guest</h2>
    <p>
      No need to even sign up to look around.  You are welcome so see the content we have so far, and can sign up anytime you like if you have anything you want to share.
    </p>
  </div>
</div>

app/views/welcome/index.html.haml
%h1 Welcome#index
%p Find me in app/views/welcome/index.html.haml
= link_to "Sign up", new_user_registration_path
= link_to "Sign In", new_user_session_path
= link_to "sign out", destroy_user_session_path, method: :delete

app/views/wikis/_form.html.erb
<%= form_for wiki do |f| %>
	<% if wiki.errors.any? %>
		<h4>Whoopsie!</h4>
		<ul>
			<% wiki.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>

	<div class='form-group'>
		<%= f.label :title %>
		<%= f.text_field :title, class: 'form-control', placeholder: 'Name of exercise?' %>
	</div>
	<div class='form-group'>
		<%= f.label :body %> (Automatically translates markdown language! To get live previewing, just click on the fullscreen button inside the editor)
		<div id='epiceditor'>
    	<%= f.text_area :body, class: 'form-control', placeholder: 'And how do we do it?' %>
    </div>
	</div>
	<% if current_user.role == 'premium' || current_user.role == 'admin' %>
		<div class='form-group'>
			<%= f.check_box :private %> Private?
		</div>
	<% end %>
	<%= f.submit "Save", class: 'btn btn-success' %>
<% end %>

<script>var editor = new EpicEditor().load()</script>

app/views/wikis/_form.html.haml
= form_for wiki do |f|
  -if wiki.errors.any?
    %h4 Whoopsie!
    %ul
      - wiki.errors.full_messages.each do |msg|
        %li= msg
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control', placeholder: "Name of exercise?"
  .form-group
    = f.label :body
    = f.text_area :body, class: 'form-control', placeholder: "And how do we do it?"
  - if current_user.role == 'premium' || current_user.role == 'admin'
    .form-group
      = f.check_box :private
      Private?
    = f.submit "Save", class: 'btn btn-success'

app/views/wikis/create.html.erb
<h1>Wikis#create</h1>
<p>Find me in app/views/wikis/create.html.erb</p>

app/views/wikis/destroy.html.erb
<h1>Wikis#destroy</h1>
<p>Find me in app/views/wikis/destroy.html.erb</p>

app/views/wikis/edit.html.haml
%h1 Edit Wiki
= render partial: 'form', locals: {wiki: @wiki}
Current Collaborators:
- @wiki.collaborators.each do |col|
  %br= col.user.name
= link_to "Add Collaborators", new_wiki_collaborator_path(@wiki)

app/views/wikis/index.html.erb
<h1>Wikis index</h1>

<% @wikis.each do |wiki| %>
	<h4><%= link_to wiki.title, wiki_path(wiki) %><h5>
  <p>
    <%= wiki.summary %>
  </p>
<% end %>

app/views/wikis/index.html.haml
%h1
- @wikis.each do |wiki|
  %p
    = link_to wiki.title, wiki_path(wiki)
    = link_to "Delete", wiki_path(wiki), method: :delete

app/views/wikis/new.html.erb
<h1>New Wiki</h1>
<div>
  <%= render partial: 'form', locals: {wiki: @wiki} %>
</div>

app/views/wikis/new.html.haml
%h1 New Wiki
= render partial: 'form', locals: {wiki: @wiki}

app/views/wikis/show.html.erb
<h1><%= @wiki.title %></h1>
<h6>Created by: <%= @wiki.user.name %></h6>
<h4><%= @wiki.summary %></h4>
<p>Public: <%= !@wiki.private %>
<h5>Steps:</h5>
<p><%= markdown(@wiki.body).html_safe %></p>
<%= link_to "edit", edit_wiki_path(@wiki) %>
<%= link_to "delete", wiki_path(@wiki), method: :delete %>

<p>
	Collaborators: <%= @wiki.user.name %>
	<% @wiki.users.each do |user| %>
		<%= ", #{user.name}" %>
	<% end %>
</p>

app/views/wikis/show.html.haml
%h1= @wiki.title
%h6 Created by: #{@wiki.user.name}
%p Private? #{@wiki.private}
%p= markdown(@wiki.body)
= link_to "edit", edit_wiki_path(@wiki)
= link_to "delete", wiki_path(@wiki), method: :delete

%p
  Collaborators: #{@wiki.user.name}
  - @wiki.users.each do |user|
    =", #{user.name}"

app/views/wikis/update.html.erb
<h1>Wikis#update</h1>
<p>Find me in app/views/wikis/update.html.erb</p>